---
title: "Quality check 03, Block group intersections with community districts"
author: "Satya Golla and Steve Simon"
date: "Created 2022-03-21"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

This program examines block groups that only partially intersect with community districts.

### Load relevant files

```{r setup}
# Important abbreviations:
#    bg = block group
#    bl = block
#    cd = community district
#    co = county
#    nbd=neighborhood
#    tr = tract

library(glue)
library(magrittr)
library(sf)
library(tidyverse)
path_name <- "../data/"
```

### Contents of bg

```{r}
load(glue("{path_name}bg.RData"))
glimpse(bg)
```

### Contents of bl

```{r}
load(glue("{path_name}bl.RData"))
glimpse(bl)
```

### Contents of cd

```{r}
load(glue("{path_name}cd.RData"))
glimpse(cd)
```

### Contents of co

```{r}
load(glue("{path_name}co.RData"))
glimpse(co)
```

### Contents of cd-intersections

```{r}
load(glue("{path_name}cd-intersections.RData"))
glimpse(bg_cd_intersection)
glimpse(bl_cd_intersection)
```

### Contents of cd-weights

```{r}
load(glue("{path_name}cd-weights.RData"))
glimpse(bg_counts)
glimpse(bg_list)
glimpse(bl_counts)
glimpse(bl_list)
```

### Subset co to seven counties

```{r}
clist <- c(
  "20091",
  "20103",
  "20209",
  "29037",
  "29047",
  "29095",
  "29165")
co                                     %>%
  filter(GEOID %in% clist)              -> co
glimpse(co)
```

### Display functions

```{r display-functions}
# These functions display people and housing units
# for various census, community, or neighborhood
# geographies.

display_bg_counts <- function(bg_counts, i_cd, i_bg) {
  # Display people and units inside community 
  # district i_cd and block group i_bg
  bg_counts                            %>%
    filter(cd_id==i_cd)                %>%
    filter(bg_id==i_bg)                %>%
    return
}

count_bl_inside_bg <- function(bl, i_bg) {
  bl                                   %>%
    mutate(
      bg_id=str_sub(bl_id, 1, 12))     %>%
    filter(bg_id==i_bg)                %>%
    pull(bl_id)                         -> bl_subset
  bl_subset                            %>%
    length                             %>%
    paste0(" blocks in bg")            %>%
    print
  bl_counts                            %>%
    filter(cd_id==i)                   %>%
    pull(bl_id)                         -> cd_list_i
  setdiff(bl_list_j, cd_list_i)        %>%
    length                             %>%
    paste0(" blocks outside cd")       %>%
    print
  bl_counts                            %>%
    filter(cd_id==i)                   %>%
    filter(bg_id==j)                   %>%
    select(
      bl_id,
      bl_prop_in,
      people_in,
      people,
      units_in,
      units)                           %>%
    data.frame                         %>%
    return
}

display_bl_inside_outside_cd <- function(bl_cd_intersection, bg, i, j) {
  # Displays counts of blocks within block
  # group j that are either inside or outside
  # community district i
}
```

### Plot functions

```{r plot-functions}
# These functions plot various census, 
# community, or neighborhood  geographies.

add_red_border <- function(mapx, geo) {
  mapx                                    +
    geom_sf(
      data=geo,
      aes(),
      fill=NA,
      color="darkred")
}

add_green_interior <- function(mapx, geo) {
  mapx                                    +
    geom_sf(
      data=geo,
      aes(),
      fill="lightgreen",
      color=NA)
}

plot_bg <- function(cd, i_cd, bg, i_bg, bl) {
  cd_subset <- filter(cd, cd_id==i_cd)
  bg_subset <- filter(bg, bg_id==i_bg)
  bl_subset <- filter(bl, str_sub(bl_id, 1, 12)==i_bg)
  int_cd_bg <- st_intersection(cd_subset, bg_subset)
  ti <- paste0(
    "Closeup of block group ", i_bg)
  ggplot(bg_subset, aes())                +
    geom_sf(
      fill=NA,
      color="darkred")                    +
    geom_sf(
      data=int_cd_bg,
      aes(),
      fill="lightgreen",
      color=NA)                +
    geom_sf(
      data=bl_subset,
      aes(),
      fill=NA,
      color="darkred")                  +
    ggtitle(ti)                         -> bg_map
  plot(bg_map)
}

plot_bl <- function(cd, i_cd, bg, i_bg, bl, i_bl) {
  cd_subset <- filter(cd, cd_id==i_cd)
  bg_subset <- filter(bg, bg_id %in% i_bg)
  bl_subset <- filter(bl, bl_id==i_bl)
  int_cd_bl <- st_intersection(cd_subset, bl_subset)
  ti <- paste0(
    "Closeup of block ", i_bl)
  ggplot(bl_subset, aes())                   +
    geom_sf(
      fill=NA,
      color="darkred")                  +
    geom_sf(
      data=int_cd_bl,
      aes(),
      fill="lightgreen",
      color=NA)               +
    ggtitle(ti)                         -> bl_map
  plot(bl_map)
}

plot_cd <- function(cd, i_cd, bg, i_bg, bg_info=i_bg) {
  cd_subset <- filter(cd, cd_id==i_cd)
  ti <- paste(cd_subset$cd_name, bg_info)
  bg_subset <- filter(bg, bg_id==i_bg)
  ggplot(cd_subset, aes())              +
    geom_sf(
      fill="lightgreen",
      color=NA)               +
    geom_sf(
      data=bg_subset,
      aes(),
      fill=NA,
      color="darkred")                  +
    ggtitle(ti)                         -> cd_map
  plot(cd_map)
}
```

### Subset cd

```{r}
cd                                     %>%
  tibble                               %>%
  distinct(cd_id)                      %>%
  arrange(cd_id)                       %>%
  pull(cd_id)                           -> cd_list
```

### High level view

```{r loop}
for (i_cd in cd_list[2:4]) {
  cd_subset <- filter(cd, cd_id==i_cd) 
  ti <- cd_subset$cd_name
  ggplot(cd_subset, aes())              +
    # geom_sf_text(co, aes(label=NAME))   +
    ggtitle(ti)                         +
    xlab("Longitude")                   +
    ylab("Latitude")                    +
    geom_sf(
      data=co,
      aes(),
      fill=NA,
      color="darkred")   +
    geom_sf(
      data=cd_subset,
      fill="lightgreen",
      color=NA)                         -> map1
  print(map1)
  next
  bg_cd_intersection                   %>%
    filter(cd_id==i_cd)                %>%
    pull(bg_id)                         -> bg_list
  bg                                   %>%
    filter(bg_id %in% bg_list)          -> bg_subset

  ggplot(cd_subset)                     +
    ggtitle(ti)                         +
    xlab("Longitude")                   +
    ylab("Latitude")                   %>%
    add_green_interior(cd_subset)      %>%
    add_red_border(bg_subset)           -> map2
  plot(map2)

  for (i_bg in bg_list) {
    bl_subset <- filter(bl, str_sub(bl_id, 1, 12)==i_bg)
    ggplot()                           %>%
      ggtitle(ti)                       +
      xlab("Longitude")                 +
      ylab("Latitude")                 %>%
      add_green_interior(cd_subset)    %>%
      add_red_border(bl_subset)         -> map3
      plot(map3)
  }
}
```

```{r}
for (i_cd in cd_list[2:4]) {
  next
  bg_n1 <- dim(bg_subset)[1]
  bg_n2 <- sum(bg_subset$bg_prop_in==1)
  bg_n3 <- sum(bg_subset$bg_prop_in > hi & bg_subset$bg_prop_in != 1)
  bg_n4 <- sum(bg_subset$bg_prop_in > lo & bg_subset$bg_prop_in <= hi)
  bg_n5 <- sum(bg_subset$bg_prop_in <= lo)
  
  bg_message <- glue(
    "{bg_n1} block groups touch or intersect community district\n",
    "{bg_n2} block groups lie entirely inside community district\n",
    "{bg_n3} block groups lie mostly inside community district\n",
    "{bg_n4} block groups lie partially inside community district\n",
    "{bg_n5} block groups lie mostly outside community district\n")
  cat(bg_message)
  plot_cd(cd, i_cd, bg, bg_subset$bg_id, "block groups touching or intersecting")
  plot_cd(cd, i_cd, bg, bg_subset$bg_id, "block groups touching or intersecting")
    for (i_bg in bg_subset$bg_id) {
    bg_cd_intersection                   %>%
      filter(cd_id==i_cd)                %>%
      filter(bg_id==i_bg)                %>%
      pull(bg_prop_in)                    -> bg_prop
    if (bg_prop < lo) next
    if (bg_prop > hi) next
    plot_cd(cd, i_cd, bg, i_bg)
    plot_bg(cd, i_cd, bg, i_bg, bl)
    bl_cd_intersection                   %>%
      filter(cd_id==i_cd)                %>%
      filter(bg_id==i_bg)                %>%
      select(bl_id, bl_prop_in)           -> bl_subset
    bl_n1 <- dim(filter(bl_cd_intersection, bg_id==i_bg))[1]
    bl_n2 <- sum(bg_subset$bg_prop_in==1)
    bl_n3 <- sum(bg_subset$bg_prop_in > hi & bg_subset$bg_prop_in != 1)
    bl_n4 <- sum(bg_subset$bg_prop_in > lo & bg_subset$bg_prop_in <= hi)
    bl_n5 <- sum(bg_subset$bg_prop_in <= lo)
    bl_n6 <- bl_n1 - bl_n2 - bl_n3 - bl_n4 - bl_n5
    bl_message <- glue(
      "{bl_n1} blocks in the block group\n",
      "{bl_n2} blocks lie entirely inside community district\n",
      "{bl_n3} blocks lie mostly inside community district\n",
      "{bl_n4} blocks lie partially inside community district\n",
      "{bl_n5} blocks lie mostly outside community district\n",
      "{bl_n6} blocks lie entirely outside community district\n")
    cat(bl_message)
    for (i_bl in bl_subset$bl_id) {
      bl_cd_intersection                 %>%
        filter(cd_id==i_cd)                %>%
        filter(bg_id==i_bg)                %>%
        filter(bl_id==i_bl)                %>%
        pull(bl_prop_in)                    -> bl_prop
      if (bl_prop > hi) next
      if (bl_prop < lo) next
      plot_bl(cd, i_cd, bg, i_bg, bl, i_bl)
    }
    bg_counts                            %>%
      filter(cd_id==i_cd)                %>%
      filter(bg_id==i_bg)                %>%
      data.frame                         %>%
      print
    bl_counts                            %>%
      filter(cd_id==i_cd)                %>%
      filter(bg_id==i_bg)                %>%
      select(-bg_id)                     %>%
      data.frame                         %>%
      print
  }
}
```
