---
title: "Test map text"
author: "Satya Golla and Steve Simon"
date: "Created 2022-07-15"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

This program tests the writing of text on maps.

### Load relevant files

```{r setup}
# Important abbreviations:
#    bg = block group
#    bl = block
#    cd = community district
#    co = county
#    nbd=neighborhood
#    tr = tract

library(glue)
library(magrittr)
library(sf)
library(tidyverse)
path_name <- "../data/"
```

### Sample code

First is an example from [HIroaki Yutani's blog][yut1]. This is the "old" way.

```{r}
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)

# use only first three elements
nc3 <- nc[1:3, ]

# choose a point on the surface of each geometry
nc3_points <- sf::st_point_on_surface(nc3)

# retrieve the coordinates
nc3_coords <- as.data.frame(sf::st_coordinates(nc3_points))
nc3_coords$NAME <- nc3$NAME

nc3_coords

ggplot() +
  geom_sf(data = nc3, aes(fill = AREA)) +
  geom_text(data = nc3_coords, aes(X, Y, label = NAME), colour = "white")
```

[yut1]: https://yutani.rbind.io/post/geom-sf-text-and-geom-sf-label-are-coming/

This is the "new" way.

```{r}
# texts and labels
p <- ggplot(nc3) +
  geom_sf(aes(fill = AREA))

p + geom_sf_text(aes(label = NAME), colour = "white")
```

### Contents of bg

```{r}
load(glue("{path_name}bg.RData"))
glimpse(bg)
```

### Contents of bl

```{r}
load(glue("{path_name}bl.RData"))
glimpse(bl)
```

### Contents of cd

```{r}
load(glue("{path_name}cd.RData"))
glimpse(cd)
```

### Contents of co

```{r}
load(glue("{path_name}co.RData"))
glimpse(co)
```

### Contents of cd-intersections

```{r}
load(glue("{path_name}cd-intersections.RData"))
glimpse(bg_cd_intersection)
glimpse(bl_cd_intersection)
```

### Contents of cd-weights

```{r}
load(glue("{path_name}cd-weights.RData"))
glimpse(bg_counts)
glimpse(bg_list)
glimpse(bl_counts)
glimpse(bl_list)
```

### Subset co to seven counties

```{r}
clist <- c(
  "20091",
  "20103",
  "20209",
  "29037",
  "29047",
  "29095",
  "29165")
co                                     %>%
  filter(GEOID %in% clist)              -> co
glimpse(co)
```

### Draw counties

The "old" way.

```{r}
co_points <- st_point_on_surface(co)
co_coords <- as.data.frame(st_coordinates(co_points))
co_coords$NAME <- co$NAME

co_coords

ggplot()+
  geom_sf(data=co, color="darkred", fill=NA)     +
  geom_text(data=co_coords, aes(X, Y, label=NAME))                           +
  xlab("Longitude")                     +
  ylab("Latitude")
```


The "new" way.

```{r}
ggplot(co, aes(label=NAME))                        +
  geom_sf(color="darkred", fill=NA)     +
  geom_sf_text()                                   +
  xlab("Longitude")                                +
  ylab("Latitude")
```
